version: "2.4"

services:
  api_flask_app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    hostname: api_flask_app
    container_name: api_flask_app
    mem_limit: 128m
    cpus: 1
    ports:
      - "9090:5050"
    volumes:
      - .:/opt/alloxentric
    env_file:
      - .env.local
    environment:
      - PORT=5050


networks:
  default:
    name: alloxentric.com