version: "2.4"

services:
  mongo:
    image: mongo:5.0
    restart: always
    hostname: mongo
    container_name: mongo
    mem_limit: 256m
    cpus: 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=supersecurePass1
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  # postgres:
  #     image: postgres:14.4
  #     hostname: postgres
  #     container_name: postgres
  #     restart: unless-stopped
  #     mem_limit: 128m
  #     cpus: 2
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  #     environment:
  #       POSTGRES_DB: keycloak
  #       POSTGRES_USER: keycloak
  #       POSTGRES_PASSWORD: keycloak_pwd

  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    hostname: keycloak
    container_name: keycloak
    restart: unless-stopped
    mem_limit: 1024m
    cpus: 4
    volumes:
      - ./themes/custom:/opt/keycloak/themes/autoenrollment
      - ./keycloak/export:/opt/keycloak/data/import
      - ./keycloak/db:/opt/keycloak/data/h2
    environment:
      # KC_DB: postgres
      # KC_DB_URL: jdbc:postgresql://postgres/keycloak
      # #KC_DB_URL_HOST: localhost
      # #KC_DB_URL_PORT: 5432
      # #KC_DB_URL_DATABASE: keycloak
      # KC_DB_USERNAME: keycloak
      # KC_DB_PASSWORD: keycloak_pwd
      # KC_DB_SCHEMA: public
      # KC_HOSTNAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: xentric
    ports:
      - 8080:8080
      - 8443:8443
    # depends_on:
    #   - postgres
    #command: start --optimized
    command: start-dev -Dkeycloak.profile.feature.upload_scripts=enabled --import-realm

volumes:
  mongodb:
  mongodb_config:
  #postgres_data:

networks:
  default:
    name: alloxentric.com